import json
import csv
import io
from typing import List, Dict, Any
from .models import CandidateReadinessReport

class ReportExporter:
    """Exports career evaluations and market benchmarks into Markdown, HTML, and CSV."""

    @staticmethod
    def to_markdown(reports: List[CandidateReadinessReport]) -> str:
        lines = [
            "# Candidate Tech Career Readiness & Roadmap Report",
            "",
            "Generated by Job Market Explorer (Hackathon 3.0)",
            "",
            "| Career Path | Match % | Status | Salary Range | Growth Outlook | Missing Skills |",
            "| :--- | :---: | :--- | :--- | :--- | :--- |"
        ]
        for r in reports:
            missing_str = ", ".join(r.missing_skills) if r.missing_skills else "None (Ready!)"
            lines.append(
                f"| **{r.role}** | `{r.match_percentage}%` | {r.status} | {r.salary_range} | {r.growth_rate} | {missing_str} |"
            )

        lines.append("")
        lines.append("## Learning Roadmaps")
        for r in reports:
            if r.missing_skills:
                lines.append(f"### Roadmap for {r.role}")
                for m in r.milestones:
                    skills_desc = ", ".join(m.skills_to_learn) if m.skills_to_learn else "Portfolio & Capstone"
                    lines.append(f"- **{m.phase_title}** (~{m.estimated_weeks} weeks): Focus on `{skills_desc}`")
                    lines.append(f"  - Deliverable: {m.key_deliverable}")
                lines.append("")

        return "\n".join(lines)

    @staticmethod
    def to_csv(reports: List[CandidateReadinessReport]) -> str:
        output = io.StringIO()
        writer = csv.writer(output)
        writer.writerow(["Role", "MatchPercentage", "Status", "SalaryRange", "GrowthRate", "MatchingSkillsCount", "MissingSkillsCount", "MissingSkills"])
        for r in reports:
            writer.writerow([
                r.role,
                r.match_percentage,
                r.status,
                r.salary_range,
                r.growth_rate,
                len(r.matching_skills),
                len(r.missing_skills),
                "; ".join(r.missing_skills)
            ])
        return output.getvalue()
